config/routes.rb
Rails.application.routes.draw do
  resources :doinits
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doinit.rb
class Doinit < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :doinits, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doinits_controller.rb
class DoinitsController < ApplicationController
  before_action :set_doinit, only: %i[ show edit update destroy ]
  include DoinitsHelper
  # GET /doinits or /doinits.json
  def index
    @doinits = Doinit.all
  end

  # GET /doinits/1 or /doinits/1.json
  def show
  end

  # GET /doinits/new
  def new
    @doinit = Doinit.new
  end

  # GET /doinits/1/edit
  def edit
  end

  # POST /doinits or /doinits.json
  def create
    @doinit = Doinit.new(doinit_params)
    @doinit = assign_post_creator(@doinit, current_user)
    respond_to do |format|
      if @doinit.save
        format.html { redirect_to @doinit, notice: "Doinit was successfully created." }
        format.json { render :show, status: :created, location: @doinit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doinit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doinits/1 or /doinits/1.json
  def update
    respond_to do |format|
      if @doinit.update(doinit_params)
        format.html { redirect_to @doinit, notice: "Doinit was successfully updated." }
        format.json { render :show, status: :ok, location: @doinit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doinit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doinits/1 or /doinits/1.json
  def destroy
    @doinit.destroy
    respond_to do |format|
      format.html { redirect_to doinits_url, notice: "Doinit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doinit
      @doinit = Doinit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doinit_params
      params.require(:doinit).permit(:title, :user_id, :importance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doinits_helper.rb
module DoinitsHelper
	def assign_doinit_creator(doinit, creator)
		doinit.user = creator
		doinit
	  end
end

app/views/doinits/_form.html.erb
<%= form_with(model: doinit, local: true) do |form| %>
  <% if doinit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doinit.errors.count, "error") %> prohibited this doinit from being saved:</h2>

      <ul>
        <% doinit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :importance %>
    <%= form.number_field :importance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doinits/edit.html.erb
<h1>Editing Doinit</h1>

<%= render 'form', doinit: @doinit %>

<%= link_to 'Show', @doinit %> |
<%= link_to 'Back', doinits_path %>

app/views/doinits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doinits</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Importance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doinits.each do |doinit| %>
      <tr>
        <td><%= doinit.title %></td>
        <td><%= doinit.importance %></td>
        <td><%= link_to 'Show', doinit %></td>
        <td><%= link_to 'Edit', edit_doinit_path(doinit) %></td>
        <td><%= link_to 'Destroy', doinit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doinit', new_doinit_path %>

app/views/doinits/new.html.erb
<h1>New Doinit</h1>

<%= render 'form', doinit: @doinit %>

<%= link_to 'Back', doinits_path %>

app/views/doinits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @doinit.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @doinit.user_id %>
</p>

<p>
  <strong>Importance:</strong>
  <%= @doinit.importance %>
</p>

<%= link_to 'Edit', edit_doinit_path(@doinit) %> |
<%= link_to 'Back', doinits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JustDoinit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>